### ISSUE TITLE
Rename repository to `vc-specs` before FPWD

### ISSUE THREAD

**Issue by msporny** [w3c/vc-specs-dir#17]
We should rename the shortname to `vc-specs`. 

We will still make it clear that the document is a directory and not an official registry, that's an important distinction to make in the document. An alternative is to expand the name to `vc-spec-directory` to align w/ `did-spec-registries`. What we have right now is a strange middle-ground in naming.

/cc @iherman @jandrieu @OR13 @mprorock @dlongley @TallTed

**Comment by OR13** [comment]
If we are treating it like a registry, we should call it a registry.

I agree the name should be changed, but it might be smart to wait for the dust to settle on the media types and extension points before we rename.

**Comment by jandrieu** [comment]
> If we are treating it like a registry, we should call it a registry.

But we aren't. It isn't a registry. It's a directory of related specifications.

Being listed confers no distinction other than the editors thought it is related. The listed specifications have no normative weight because they are listed. The only impact is that others are more readily able to find specifications building on Verifiable Credentials.

Anyone else could put together such a directory and it might be just as useful or moreso.

**Comment by iherman** [comment]
If the rename should occur, this is on me to do it. Has there ever been a consensus on doing this?

@brentzundel @Sakurann

**Comment by brentzundel** [comment]
I no dot believe we have made an official resolution here, but not sure it is necessary just for the name of the repository. Are we also proposing a change to the short-name and Note?

**Comment by iherman** [comment]
@brentzundel poor choice of words: there is no need for a formal WG RESOLUTION for something like that, but only a lower-case resolution. ***I*** need that before we proceed.

As far as the change of the short-name, there isn't any official WG publication of that spec yet. The only resolution is from [last March](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-03-01-vcwg#resolution1) which says:

> Adopt https://msporny.github.io/vc-specs-directory/ as the "VC Specs Directory" work item in the VCWG tentatively using the shortname vc-spec-dir, converting all concerns raised during the call to issues in the Github repository.

the operative term being "tentatively". I.e., renaming the repository is the only action right now, anything related to the publication is still ahead of us...

**Comment by iherman** [comment]
We have resolved, yesterday, to publish this document under the current name. I presume it means this issue is moot and should be closed without further actions, @msporny @brentzundel ?

**Comment by msporny** [comment]
> We have resolved, yesterday, to publish this document under the current name. I presume it means this issue is moot and should be closed without further actions, @msporny @brentzundel ?

All it means is that I forgot to bring it up to the group before we made the resolution. :P

I continue to insist that this github repository is "**A**" registry, not "**THE**" registry, of related VC specifications. I'd prefer we call it "A VC Specifications Registry" and have clarifying text that it doesn't need to be the only one, and change the short name to "vc-specs".

Failing all of that, I'd still prefer the shortname to be "vc-specs" so it doesn't assert whether it's a directory or a registry in the short name (we let the title of the specification and prose in the specification do that).

All that said, if no one else feels strongly about this, we can close the issue.

**Comment by iherman** [comment]
No comment in three weeks, @msporny's remark leads to close this.
