### ISSUE TITLE
Add an example JSON file the "how to register" section

### ISSUE THREAD

**Issue by jandrieu** [w3c/vc-specs-dir#3]
Seems to me that parsing YAML is a fairly high barrier. An example would help.

**Comment by OR13** [comment]
Ahh, I didn't realize this was about the respec.

Seems very easy to fix, given there are examples in the PR template and readme.

And several merged PRs at this point.

@jandrieu would you be willing to do a PR?

**Comment by OR13** [comment]
@jandrieu can you please review https://github.com/w3c/vc-specs-dir/pull/10

Let me know if you want more.

**Comment by jandrieu** [comment]
Reviewed. Looks good.
